In [27]:
import torch

### Creation of Tensors

In [28]:
zerod = torch.tensor(42)
print(zerod)
print(zerod.shape)
print(zerod.ndim)

tensor(42)
torch.Size([])
0


In [29]:
oned = torch.tensor([1,2])
print(oned)
print(oned.shape)
print(oned.ndim)

tensor([1, 2])
torch.Size([2])
1


In [30]:
twod = torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
print(twod)
print(twod.shape)
print(twod.ndim)

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])
torch.Size([3, 3])
2


In [31]:
threed = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(threed)
print(threed.ndim)
print(threed.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])


### GPU conversion

In [32]:
if torch.cuda.is_available():
  gpu_tensor = oned.to('cuda')
  print(gpu_tensor)
else:
  print("Cuda not available on this machine")


Cuda not available on this machine


In [33]:
print("Number of Elements : ", threed.numel())

Number of Elements :  8


### Slicing

In [34]:
twod

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [35]:
twod[:,1] #Returns the second column of the twod tensor

tensor([2, 4, 6])

In [36]:
twod[:2] #Returns the first two rows with all the columns

tensor([[1, 2, 3],
        [3, 4, 5]])

In [37]:
twod[:,:2] #Returns the first two columns with all the rows

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [38]:
twod[1,1] #returns the exact element at the position

tensor(4)

In [39]:
twod[1,1:] #returns only element of row 1 and columns 1 and 2 (all cols from 1)

tensor([4, 5])

In [40]:
#Getting two elements from different positions
# We will take 2 and 5, 2 is in the position (O,1) and 5 is in the position (1,2)
twod[[0,1],[1,2]] #Here inside the list the first 1d collects the rows and second 1d collects the cols 0 and 1 are the rows of both the nums and 1 and 2 are the cols of both the nums

tensor([2, 5])

### Conditions

In [41]:
twod[twod>1] #Prints all the elements that are satisfying the given condition

tensor([2, 3, 3, 4, 5, 5, 6, 7])

### Replace

In [42]:
print(twod) #Change single val
twod[0,1] = 10
twod

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])


tensor([[ 1, 10,  3],
        [ 3,  4,  5],
        [ 5,  6,  7]])

In [43]:
print(twod) #Change Multiple values from between rows and cols
twod[0,1:]=torch.tensor([5,6])
twod

tensor([[ 1, 10,  3],
        [ 3,  4,  5],
        [ 5,  6,  7]])


tensor([[1, 5, 6],
        [3, 4, 5],
        [5, 6, 7]])

In [44]:
print(twod) #Changing the complete row value of row 1
twod[1,:] = torch.tensor([6,7,8])

tensor([[1, 5, 6],
        [3, 4, 5],
        [5, 6, 7]])


In [45]:
twod

tensor([[1, 5, 6],
        [6, 7, 8],
        [5, 6, 7]])

### Advanced Slicing

In [46]:
indices = torch.tensor([0,2]) #when dim = 0, we get to select the rows and the torch.tensor([0,2]) is necessary, we can either put that into the index or we need to store it in a seperate variable and then use it
selected_rows = torch.index_select(twod,dim=0,index=indices)
selected_rows

tensor([[1, 5, 6],
        [5, 6, 7]])

In [47]:
indices = torch.tensor([0,2]) #when dim=1, we get to select the cols
selected_rows = torch.index_select(twod,dim=1,index=indices)
selected_rows

tensor([[1, 6],
        [6, 8],
        [5, 7]])

In [48]:
twod[:,::2] # Here we use Step, ie, we select all the rows, then start from the first col, the skip one col, print the next col, hence it has printed zeroth and last column

tensor([[1, 6],
        [6, 8],
        [5, 7]])

In [49]:
torch.flip(twod,dims=(0,)) #This will flip all the rows

tensor([[5, 6, 7],
        [6, 7, 8],
        [1, 5, 6]])

In [50]:
print(twod) #Flips all the columns
twod=torch.flip(twod,dims=[1])
twod

tensor([[1, 5, 6],
        [6, 7, 8],
        [5, 6, 7]])


tensor([[6, 5, 1],
        [8, 7, 6],
        [7, 6, 5]])

### Memory Allocation

In [53]:
float16_tensor = torch.ones(1000, dtype=torch.float16)
float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)

print(float16_tensor.element_size())
print(float32_tensor.element_size())
print(float64_tensor.element_size())
print(float16_tensor.nelement())
print("Memory taken by float16 :", float16_tensor.element_size()*float16_tensor.nelement())
print("Memory taken by float32 :", float32_tensor.element_size()*float32_tensor.nelement())
print("Memory taken by float64 :", float64_tensor.element_size()*float64_tensor.nelement())

2
4
8
1000
Memory taken by float16 : 2000
Memory taken by float32 : 4000
Memory taken by float64 : 8000


### Concatenation of Tensors (Joining Tensors)

First we use .cat which allows the joining of tensors without altering the dimensions of the tensors

In [55]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])
joined_tensor_row = torch.cat((tensor1,tensor2),dim=0)
joined_tensor_col = torch.cat((tensor1,tensor2),dim=1)
print(joined_tensor_row)
print(joined_tensor_col)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


Next we use .stack which will modify the dimensions of the tensors

In [58]:
joined_tensor_row_stack = torch.stack((tensor1,tensor2),dim=0)
joined_tensor_col_stack = torch.stack((tensor1,tensor2),dim=1)
print(joined_tensor_row_stack)
print(joined_tensor_col_stack)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


### Splitting of Tensors

First we use .chunk to split the tensors into equal sized chunks, it will split it into n number of chunks, but all the chunks will have same number of elements

In [64]:
tensor = torch.arange(12)
chunked_tensor = torch.chunk(tensor,6,dim=0)
chunked_tensor

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10, 11]))

Here even though we give 5, the split is only happened into 4 chunks, this is becoz, when split in 5, all chunks will not have same number of elements, hence it will look for the previous vals where the split is equal and take that value as default, this wont happen in .split

In [68]:
chunked_tensor_2 = torch.chunk(tensor,5,dim=0)
chunked_tensor_2

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))

Whereas if we use split, then the split will happen based on the number of elements, ex, if 5, then each part will have 5 elements in it

In [66]:
split_tensor = torch.split(tensor,5,dim=0)
split_tensor

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))

### Reshaping a Tensor

In [ ]:
normal_tensor = torch.arange(24)
tensor_reshape = torch.arange(24).reshape(12,2)
print(normal_tensor)
tensor_reshape

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])

### Transposing

In [ ]:
transpose_tensor = tensor_reshape.transpose(0,1) #When we transpose 0 and 1, we actually have the dimensions as (12,2), here it will get swapped into (2,12)
print(tensor_reshape)
print(transpose_tensor)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
